name: vedem
description: "O aplicatie simpla, complet locala, in flutter folosind clean architecture cu bloc, in care poti adauga taskuri cu diamante in fiecare zi si poti pune o poza drept daily highlight."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.1.0
  http: ^1.4.0
  shared_preferences: ^2.5.3
  fpdart: ^1.1.1
  internet_connection_checker_plus: ^2.7.2
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  uuid: ^4.5.1
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  async: ^2.13.0
  flutter_animate: ^4.5.2
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.6
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/figtree/Figtree-Regular.ttf
        - asset: assets/fonts/figtree/Figtree-Bold.ttf
          weight: 700
  assets:
    - assets/
